apiVersion: skaffold/v1beta15
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "latest"
  artifacts:
  - image: 8baller/api-node
    context: ./api_node
#   - image: 8baller/gateway
#     context: ./gateway
