apiVersion: skaffold/v1beta15
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "latest"
  artifacts:
  - image: 8ball030/api-node
    context: ./api_node
#  - image: 8ball030/gateway
#    context: ./gateway
